name = "breadbar"
description = "Minimal status bar and notification daemon for Hyprland"
binaries = ["breadbar"]
system_deps = ["gtk4", "gtk4-layer-shell", "wireplumber", "pipewire-pulse", "brightnessctl", "iw"]
optional_system_deps = ["hyprland"]
bread_deps = ["bread"]
license_file = "LICENSE"

[config]
dir = "~/.config/breadbar"

[install]
post_install = []
